### ISSUE TITLE
Excess files for icons

### ISSUE THREAD

**Issue by innoflash** [richardHaggioGwati/Instagram#1]
[https://github.com/richardHaggioGwati/Instagram/blob/d1fa48d320acbf129771e924e6867297e5219041/components/Icons/BookMark.tsx#L5-L21](https://github.com/richardHaggioGwati/Instagram/blob/d1fa48d320acbf129771e924e6867297e5219041/components/Icons/BookMark.tsx#L5-L21)

You do not need to create a component each time you have an icon..

Try to make use of icon libraries and u will see this folder can entirely disappear. 

See:

- [https://icons.getbootstrap.com/](https://icons.getbootstrap.com/)
- [https://fontawesome.com/icons](https://fontawesome.com/icons)
- [https://feathericons.com/](https://feathericons.com/)
- [https://fonts.google.com/icons](https://fonts.google.com/icons)

**Comment by richardHaggioGwati** [comment]
Resolved using Heroicons
https://github.com/richardHaggioGwati/Instagram/blob/1e9a8a2dbffbb747dd881e1b4242005b79c96096/components/Header.tsx#L6-L14
