### ISSUE TITLE
Too many keys for your props

### ISSUE THREAD

**Issue by innoflash** [richardHaggioGwati/Instagram#3]
https://github.com/richardHaggioGwati/Instagram/blob/d1fa48d320acbf129771e924e6867297e5219041/components/Post.tsx#L16

Always make sure you minimize the props you are expecting, from the looks of it all of the information you are requesting is all post related. Instead you should just pass a `post` as prop (of type object).
This avoids you have to call <Post> as below. What if the post starts gaining more properties and you have a mega project with a number of places using the Post component. You will be fucked so sending in the compound object saves you all this.

https://github.com/richardHaggioGwati/Instagram/blob/d1fa48d320acbf129771e924e6867297e5219041/components/Posts.tsx#L28-L34

**Comment by innoflash** [comment]
Same goes for your Stories

**Comment by richardHaggioGwati** [comment]
I will definitely work on that.

**Comment by richardHaggioGwati** [comment]
Issue should be resolved
https://github.com/richardHaggioGwati/Instagram/blob/1e9a8a2dbffbb747dd881e1b4242005b79c96096/components/Posts.tsx#L31
