### ISSUE TITLE
Dummy Data fetching

### ISSUE THREAD

**Issue by innoflash** [richardHaggioGwati/Instagram#4]
Here is a source of dummy demo apis for your pages.

[https://apipheny.io/free-api](https://apipheny.io/free-api)

This way it also gives you credibility when working with RESTful apis

https://github.com/richardHaggioGwati/Instagram/blob/d1fa48d320acbf129771e924e6867297e5219041/components/Posts.tsx#L3-L22

**Comment by richardHaggioGwati** [comment]
The plan was to fetch the data from firebase directly

**Comment by richardHaggioGwati** [comment]
For the dummy data, I have used fakerjs for now
https://github.com/richardHaggioGwati/Instagram/blob/1e9a8a2dbffbb747dd881e1b4242005b79c96096/components/Posts.tsx#L16-L24
